# Generated by Django 4.2 on 2023-05-12 12:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guns', '0005_alter_gun_options_gun_barrel_length_gun_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gun',
            name='barrel_length',
            field=models.FloatField(help_text='Zadejte délku hlavně zbraně v milimetrech', validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(2000.0)], verbose_name='Délka hlavně zbraně (mm)'),
        ),
        migrations.AlterField(
            model_name='gun',
            name='length',
            field=models.FloatField(help_text='Zadejte délku zbraně v milimetrech', validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(2000.0)], verbose_name='Celková délka zbraně (mm)'),
        ),
        migrations.AlterField(
            model_name='gun',
            name='weight',
            field=models.FloatField(help_text='Zadejte hmotnost zbraně v gramech', validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(20000.0)], verbose_name='Celková hmotnost zbraně (g)'),
        ),
    ]
