# Generated by Django 4.2 on 2023-06-15 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guns', '0008_inventor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventor',
            name='foto',
        ),
    ]
