# Generated by Django 4.2 on 2023-06-16 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guns', '0010_gun_inventor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gun',
            name='description',
            field=models.TextField(blank=True, help_text='Popište tuto zbraň (historie, vlastnosti, zvláštnosti...)', verbose_name='Popis zbraně'),
        ),
        migrations.AlterField(
            model_name='gun',
            name='inventor',
            field=models.ManyToManyField(blank=True, help_text='Vyberte vynálezces zbraně', to='guns.inventor'),
        ),
        migrations.AlterField(
            model_name='gun',
            name='maker',
            field=models.ManyToManyField(blank=True, help_text='Vyberte výrobce zbraně', to='guns.maker'),
        ),
        migrations.AlterField(
            model_name='maker',
            name='address',
            field=models.CharField(blank=True, help_text='Zadejte adresu firmy nebo výrobce, pokud je známá.', max_length=150, verbose_name='Adresa firmy/výrobce'),
        ),
    ]
# Generated by Django 4.2 on 2023-06-16 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guns', '0010_gun_inventor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gun',
            name='description',
            field=models.TextField(blank=True, help_text='Popište tuto zbraň (historie, vlastnosti, zvláštnosti...)', verbose_name='Popis zbraně'),
        ),
        migrations.AlterField(
            model_name='gun',
            name='inventor',
            field=models.ManyToManyField(blank=True, help_text='Vyberte vynálezces zbraně', to='guns.inventor'),
        ),
        migrations.AlterField(
            model_name='gun',
            name='maker',
            field=models.ManyToManyField(blank=True, help_text='Vyberte výrobce zbraně', to='guns.maker'),
        ),
        migrations.AlterField(
            model_name='maker',
            name='address',
            field=models.CharField(blank=True, help_text='Zadejte adresu firmy nebo výrobce, pokud je známá.', max_length=150, verbose_name='Adresa firmy/výrobce'),
        ),
    ]
