# Generated by Django 4.2 on 2023-06-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guns', '0011_alter_gun_description_alter_gun_inventor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gun',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='guns/posters/', verbose_name='Poster'),
        ),
    ]
