# Generated by Django 4.2 on 2023-05-11 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Zadejte označení zbraně', max_length=100, unique=True, verbose_name='Označení zbraně')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
