# Generated by Django 4.2 on 2023-05-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guns', '0002_type_delete_gun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(help_text='Zadejte název typu', max_length=50, unique=True, verbose_name='Označení typu'),
        ),
    ]
