# Generated by Django 4.2 on 2023-05-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guns', '0003_alter_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Zadejte označení zbraně', max_length=100, unique=True, verbose_name='Označení zbraně')),
            ],
        ),
        migrations.AddField(
            model_name='type',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Popis a charakteristika typu'),
        ),
    ]
