# Generated by Django 4.2 on 2023-05-12 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guns', '0006_alter_gun_barrel_length_alter_gun_length_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Zadejte název výrobce nebo firmy', max_length=100, unique=True, verbose_name='Název firmy/výrobce')),
                ('address', models.CharField(help_text='Zadejte adresu firmy nebo výrobce, pokud je známá.', max_length=150, verbose_name='Adresa firmy/výrobce')),
                ('about', models.TextField(blank=True, max_length=300, null=True, verbose_name='O vyrábějící firmě nebo výrobci zbraně')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='gun',
            name='maker',
            field=models.ManyToManyField(help_text='Vyberte výrobce zbraně', to='guns.maker'),
        ),
    ]
